### ISSUE TITLE
`tsdoc-param-tag-with-invalid-name` is incorrectly reported for certain identifiers (issue #148)

### ISSUE THREAD

**Issue by iclanton** [Microsoft/tsdoc#148]
A `@param` tag for a parameter called `type` (i.e. - `@param type - ...`) gives this error:

```
(tsdoc-param-tag-with-invalid-name) The @param block should be followed by a valid parameter name: The identifier "type" must be quoted because it is a TSDoc system selector name
```

But changing the tag to `@param "type" - ...`, causes this error:

```
(tsdoc-param-tag-with-invalid-name) The @param block should be followed by a parameter name
```

This makes it impossible to document a parameter called `type`.

**Comment by octogonz** [comment]
Fixed by https://github.com/Microsoft/tsdoc/pull/149

**Comment by diegosogari** [comment]
The same thing still happens for `@link` tags. For example, `{@link type}` gives this error:

    tsdoc-reference-unquoted-identifier: The identifier "type" must be quoted because it is a TSDoc system selector name  tsdoc/syntax
